/**
 * Security utilities: input sanitization, validation, and safe rendering.
 *
 * This module provides client-side validation and sanitization for user inputs
 * in the Microstore app. Since the app stores all data in IndexedDB (no server),
 * sanitization happens at the point of data entry in Zustand stores.
 */
import DOMPurify from 'dompurify';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Base58 character set used by Solana addresses */
const BASE58_REGEX = /^[1-9A-HJ-NP-Za-km-z]+$/;

/** Phone number: digits only, 7-15 digits */
const PHONE_REGEX = /^[0-9]{7,15}$/;

/** Valid CDN / trusted origins for photo URLs */
const ALLOWED_PHOTO_ORIGINS: readonly string[] = [
  'vercel-storage.com',
  'vercel.app',
  'blob.vercel-storage.com',
  'ipfs.io',
  'arweave.net',
  'cloudinary.com',
];

// ---------------------------------------------------------------------------
// HTML sanitization (for text fields)
// ---------------------------------------------------------------------------

/**
 * Strip all HTML tags from a string. Use for plain-text fields (shop name,
 * SKU, category, customer name, memo, etc.) — anything that should never
 * contain markup.
 */
export function stripHtml(input: string): string {
  if (!input) return '';
  // Use DOMPurify to strip all tags (ALLOWED_TAGS empty)
  return DOMPurify.sanitize(input, {
    ALLOWED_TAGS: [],
    ALLOWED_ATTR: [],
    KEEP_CONTENT: true,
  });
}

/**
 * Sanitize rich-text HTML (item description).
 * Allows a safe subset of formatting tags. Strips scripts, event handlers,
 * style attributes, and other dangerous content.
 */
export function sanitizeRichHtml(input: string): string {
  if (!input) return '';
  return DOMPurify.sanitize(input, {
    ALLOWED_TAGS: [
      'b', 'i', 'em', 'strong', 'u', 's', 'del',
      'p', 'br', 'hr',
      'ul', 'ol', 'li',
      'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
      'blockquote', 'pre', 'code',
      'a', 'span', 'div',
    ],
    ALLOWED_ATTR: ['href', 'target', 'rel'],
    ALLOW_DATA_ATTR: false,
    ALLOWED_URI_REGEXP: /^(?:(?:https?|mailto|tel):|[^a-z]|[a-z+.-]+(?:[^a-z+.-:]|$))/i,
  });
}

// ---------------------------------------------------------------------------
// Solana wallet validation
// ---------------------------------------------------------------------------

/**
 * Validate a Solana base58 public key.
 * Returns true for valid addresses, false otherwise.
 * Accepts empty string (optional field).
 */
export function isValidSolanaAddress(address: string): boolean {
  if (!address || address.trim() === '') return true; // optional field
  const cleaned = address.trim();
  // Base58 addresses are 32-44 characters
  if (cleaned.length < 32 || cleaned.length > 44) return false;
  return BASE58_REGEX.test(cleaned);
}

// ---------------------------------------------------------------------------
// Phone validation
// ---------------------------------------------------------------------------

/**
 * Strip non-digit characters from a phone number and validate.
 * Returns the cleaned phone string if valid, empty string if not.
 */
export function sanitizePhone(input: string): string {
  if (!input) return '';
  const digits = input.replace(/\D/g, '');
  if (digits.length < 7 || digits.length > 15) return '';
  return digits;
}

// ---------------------------------------------------------------------------
// URL / photo URL validation
// ---------------------------------------------------------------------------

/**
 * Validate a photoUrl value. Allows:
 *  - blob: URLs (generated by file upload / URL.createObjectURL)
 *  - Empty string (no photo)
 *  - URLs from trusted CDN origins
 *
 * Returns the URL if valid, empty string otherwise.
 */
export function sanitizePhotoUrl(url: string | null | undefined): string {
  if (!url) return '';
  const trimmed = url.trim();

  // blob: URLs are generated locally — safe
  if (trimmed.startsWith('blob:')) return trimmed;

  // data: URLs — reject (could be SVG XSS, and we don't expect them)
  if (trimmed.startsWith('data:')) return '';

  try {
    const parsed = new URL(trimmed);
    // Only allow https URLs
    if (parsed.protocol !== 'https:') return '';

    // Check against allowed origins
    const hostname = parsed.hostname.toLowerCase();
    for (const allowed of ALLOWED_PHOTO_ORIGINS) {
      if (hostname === allowed || hostname.endsWith('.' + allowed)) {
        return trimmed;
      }
    }

    // If not in the explicit allowlist, reject
    return '';
  } catch {
    // Not a valid URL
    return '';
  }
}

// ---------------------------------------------------------------------------
// Text field sanitization (strip HTML + trim)
// ---------------------------------------------------------------------------

/**
 * Sanitize a plain-text field: strip HTML, trim, and enforce max length.
 */
export function sanitizeTextField(input: string, maxLength?: number): string {
  const stripped = stripHtml(input).trim();
  if (maxLength && stripped.length > maxLength) {
    return stripped.slice(0, maxLength);
  }
  return stripped;
}

// ---------------------------------------------------------------------------
// Reusable DOMPurify instance for use in React components
// ---------------------------------------------------------------------------

/**
 * Get a pre-configured DOMPurify instance for sanitizing rich text HTML
 * before rendering with dangerouslySetInnerHTML.
 */
export function sanitizeHtml(html: string): string {
  return sanitizeRichHtml(html);
}
